=== nvaccess/addon-datastore/validation/_validate/addonVersion_schema.json
{
	"examples": [
		{
			"addonId": "easyAddonTech.XYZ",
			"addonVersionNumber": {
				"major": 21,
				"minor": 6,
				"patch": 0
			},
			"addonVersionName": "21.6.0",
			"displayName": "My addon",
			"publisher": "easyAddonTech",
			"description": "Makes doing XYZ easier",
			"homepage": "https://github.com/nvaccess/addon-datastore",
			"minNVDAVersion": {
				"major": 2019,
				"minor": 3,
				"patch": 0
			},
			"lastTestedVersion": {
				"major": 2020,
				"minor": 4,
				"patch": 0
			},
			"channel": "beta",
			"URL": "https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon",
			"sha256": "69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82",
			"sourceURL": "https://github.com/nvaccess/addon-datastore/",
			"license": "GPL v2",
			"licenseURL": "https://github.com/nvaccess/addon-datastore/license.MD",
			"changelog": "New features",
			"translations": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248",
			"submissionTime": 1723523492363
		}
	],
	"title": "Root",
	"type": "object",
	"description": "Information about an addon release",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"required": [
		"addonId",
		"addonVersionNumber",
		"addonVersionName",
		"displayName",
		"publisher",
		"description",
		"minNVDAVersion",
		"lastTestedVersion",
		"channel",
		"URL",
		"sha256",
		"sourceURL",
		"license",
		"translations"
	],
	"properties": {
		"addonId": {
			"default": "",
			"description": "The ID for the addon, matches the name field in the addon manifest and the folder name for the submission.",
			"examples": [
				"easyAddonTech.XYZ"
			],
			"title": "The ID for the addon",
			"type": "string"
		},
		"addonVersionNumber": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The addon version number",
			"description": "Pure numerical representation of the version being released.",
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			]
		},
		"addonVersionName": {
			"title": "The addon version name",
			"description": "The addon version being released. Must match the version in the addon manifest and the file name for the submission.",
			"type": "string",
			"default": "",
			"examples": [
				"21.6.0",
				"21.6",
				"21.06"
			]
		},
		"displayName": {
			"default": "",
			"description": "The name that will be displayed in English for the addon.",
			"examples": [
				"My addon"
			],
			"title": "The display name (en) of the addon",
			"type": "string"
		},
		"publisher": {
			"default": "",
			"description": "The name of the individual, group, or company responsible for the addon.",
			"examples": [
				"NV Access"
			],
			"title": "The publisher name for the addon",
			"type": "string"
		},
		"description": {
			"default": "",
			"description": "The English description of the addon that will be displayed for the addon.",
			"examples": [
				"Makes doing XYZ easier"
			],
			"title": "The description (en) of the addon",
			"type": "string"
		},
		"homepage": {
			"default": "",
			"description": "If the addon has a homepage where users can get more information about the addon, you can specify it here.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore"
			],
			"pattern": "^https:.*",
			"title": "The homepage URL for the addon.",
			"type": "string"
		},
		"minNVDAVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"default": {},
			"title": "The minNVDAVersion schema",
			"description": "The addon will not work with versions of NVDA prior to this version.",
			"examples": [
				{
					"major": 2019,
					"minor": 3,
					"patch": 0
				}
			]
		},
		"lastTestedVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The lastTestedVersion schema",
			"description": "The add-on has been tested up to and including this version of NVDA",
			"default": {},
			"examples": [
				{
					"major": 2020,
					"minor": 4,
					"patch": 0
				}
			]
		},
		"channel": {
			"default": "",
			"description": "Used to define pre-release (beta) add-ons. Should be either 'stable', 'beta' or 'dev'",
			"examples": [
				"beta"
			],
			"title": "The channel for the addon",
			"enum": [
				"stable",
				"beta",
				"dev"
			],
			"type": "string"
		},
		"URL": {
			"default": "",
			"description": "To allow directly downloading the *.nvda-addon file. The URL should remain valid indefinitely. GitHub release URLs are recommended.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon"
			],
			"title": "The URL to download the add-on.",
			"type": "string"
		},
		"sha256": {
			"default": "",
			"description": "Use the python script '_tools/genSha256.py' to generate this value.",
			"examples": [
				"69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82"
			],
			"title": "The sha256 for the *.nvda-addon file.",
			"type": "string"
		},
		"sourceURL": {
			"default": "",
			"description": "Allows reviewers to inspect the source code for common issues.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/"
			],
			"title": "The URL for the add-on source",
			"type": "string"
		},
		"license": {
			"default": "",
			"description": "The short name of the license.",
			"examples": [
				"GPL v2"
			],
			"title": "The short name of the license for the addon",
			"type": "string"
		},
		"licenseURL": {
			"default": "",
			"description": "A URL to the full license for the addon.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/license.MD"
			],
			"title": "The URL of the license",
			"type": "string"
		},
		"changelog": {
			"default": "",
			"description": "Changes between the previous and the current version",
			"examples": [
				"New feature"
			],
			"title": "Add-on changelog (en)",
			"type": "string"
		},
		"legacy": {
			"default": false,
			"description": "Legacy add-ons have invalid data or manifest. Legacy add-ons are not listed in the NVDA add-on store.",
			"examples": [
				true
			],
			"title": "Mark add-on as legacy",
			"type": "boolean"
		},
		"translations": {
			"default": [],
			"description": "A collection of translations generated from localized add-on manifests",
			"examples": [
				[
					{
						"language": "de",
						"displayName": "Mein Addon",
						"description": "erleichtert das Durchführen von xyz",
						"changelog": "Neue Funktionen"
					}
				]
			],
			"title": "Translations",
			"type": "array",
			"items": {
				"$ref": "#/$defs/translation"
			}
		},
		"reviewUrl": {
			"default": "",
			"description": "A URL to the discussion comment to review the add-on version.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248"
			],
			"title": "Discussion comment URL",
			"type": "string"
		},
		"submissionTime": {
			"default": 0,
			"description": "Timestamp in milliseconds, corresponding to the submission time of the add-on",
			"examples": [
				1723523492363
			],
			"title": "Submission time",
			"type": "number"
		},
		"vtScanUrl": {
			"default": "",
			"description": "A URL to the Virus Total scan for the add-on version.",
			"examples": [
				"https://www.virustotal.com/gui/file/3fda88d598e9747b2dfadfdfb8930a737c0049e9782392bffcd59ef668821547"
			],
			"title": "VirusTotal scan URL",
			"type": "string"
		},
		"scanResults": {
			"default": {},
		"description": "Results from VirusTotal scanning.",
			"examples": [
				{
					"virusTotal": {}
				}
			],
			"title": "Scan results",
			"type": "object"
		}
	},
	"$defs": {
		"canonicalVersion": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			],
			"required": [
				"major",
				"minor",
				"patch"
			],
			"properties": {
				"major": {
					"default": 0,
					"description": "'major' in major.minor.patch",
					"examples": [
						21,
						2019,
						2021
					],
					"title": "The 'major' part of the version number.",
					"type": "integer"
				},
				"minor": {
					"default": 0,
					"description": "The 'minor' part in major.minor.patch",
					"examples": [
						3
					],
					"title": "The 'minor' part of the version number.",
					"type": "integer"
				},
				"patch": {
					"default": 0,
					"description": "The 'patch' part in major.minor.patch",
					"examples": [
						0
					],
					"title": "The 'patch' part of the version number.",
					"type": "integer"
				}
			}
		},
		"translation": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"required": [
				"language",
				"displayName",
				"description"
			],
			"properties": {
				"language": {
					"default": "",
					"description": "Language code supported by NVDA",
					"examples": [
						"de",
						"pt_BR"
					],
					"title": "Language code",
					"type": "string"
				},
				"displayName": {
					"default": "",
					"description": "The translated name that will be displayed for the addon.",
					"examples": [
						"Mein Addon"
					],
					"title": "Translated display name",
					"type": "string"
				},
				"description": {
					"default": "",
					"description": "Translated description that will be displayed for the addon.",
					"examples": [
						"erleichtert das Durchführen von xyz"
					],
					"title": "The translated description",
					"type": "string"
				},
				"changelog": {
					"default": "",
					"description": "Translated description of changes between the previous and this add-on version",
					"examples": [
						"Neue Funktionen"
					],
					"title": "The translated changelog",
					"type": "string"
				}
			}
		}
	}
}

=== nvaccess/addon-datastore/addons/xPlorer/2026.3.0.json
{
	"addonId": "xPlorer",
	"displayName": "xPlorer",
	"URL": "https://github.com/chaichaimee/xPlorer/releases/download/2026.3-beta/xPlorer-v2026.3-beta.nvda-addon",
	"description": "Improve access to File Explorer.\nHot Keys:\nNVDA+Shift+X : Open xPlorer Context Menu\nNVDA+Shift+z Single Tap : Say Size\nNVDA+Shift+Z Double Tap : Compress Zip\nNVDA+Shift+C Single Tap : Copy Selected File and Folder Names\nNVDA+Shift+C Double Tap : Copy Address Bar Current Folder\nNVDA+Shift+V Single Tap : Copy Content\nNVDA+Shift+V Double Tap : Invert Selection\nNVDA+Shift+F2 : Rename File Only",
	"sha256": "277f61b36b9cb7ea8680afa7a9fe0c899e4aa93323831aa462467ec381d55114",
	"addonVersionName": "2026.3",
	"addonVersionNumber": {
		"major": 2026,
		"minor": 3,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2022,
		"minor": 4,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "chaichaimee",
	"sourceURL": "https://github.com/chaichaimee/xPlorer",
	"license": "GPL v2",
	"homepage": "https://github.com/chaichaimee/xPlorer",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1771046796000,
	"translations": [
		{
			"language": "de",
			"displayName": "xPlorer",
			"description": "Verbesserter Zugriff auf den Datei-Explorer.\nTastenkombinationen:\nNVDA+Shift+X : xPlorer-Kontextmenü öffnen\nNVDA+Shift+Z Einmal drücken : Größe ansagen\nNVDA+Shift+Z Zweimal drücken : Als ZIP komprimieren\nNVDA+Shift+C Einmal drücken : Namen der ausgewählten Dateien und Ordner kopieren\nNVDA+Shift+C Zweimal drücken : Pfad der Adressleiste des aktuellen Ordners kopieren\nNVDA+Shift+V Einmal drücken : Inhalt kopieren\nNVDA+Shift+V Zweimal drücken : Auswahl umkehren\nNVDA+Shift+F2 : Nur Datei umbenennen"
		},
		{
			"language": "en",
			"displayName": "xPlorer",
			"description": "Improve access to File Explorer.\nHot Keys:\nNVDA+Shift+X : Open xPlorer Context Menu\nNVDA+Shift+z Single Tap : Say Size\nNVDA+Shift+Z Double Tap : Compress Zip\nNVDA+Shift+C Single Tap : Copy Selected File and Folder Names\nNVDA+Shift+C Double Tap : Copy Address Bar Current Folder\nNVDA+Shift+V Single Tap : Copy Content\nNVDA+Shift+V Double Tap : Invert Selection\nNVDA+Shift+F2 : Rename File Only"
		},
		{
			"language": "es",
			"displayName": "xPlorer",
			"description": "Mejora el acceso al Explorador de archivos.\nTeclas rápidas:\nNVDA+Shift+X : Abrir el menú contextual de xPlorer\nNVDA+Shift+Z Un toque : Decir tamaño\nNVDA+Shift+Z Dos toques : Comprimir en Zip\nNVDA+Shift+C Un toque : Copiar nombres de archivos y carpetas seleccionados\nNVDA+Shift+C Dos toques : Copiar la barra de direcciones de la carpeta actual\nNVDA+Shift+V Un toque : Copiar contenido\nNVDA+Shift+V Dos toques : Invertir selección\nNVDA+Shift+F2 : Renombrar solo archivo"
		},
		{
			"language": "fr",
			"displayName": "xPlorer",
			"description": "Améliore l'accès à l'Explorateur de fichiers.\nTouches de raccourci :\nNVDA+Shift+X : Ouvrir le menu contextuel xPlorer\nNVDA+Shift+Z Une pression : Annoncer la taille\nNVDA+Shift+Z Deux pressions : Compresser en Zip\nNVDA+Shift+C Une pression : Copier les noms des fichiers et dossiers sélectionnés\nNVDA+Shift+C Deux pressions : Copier la barre d'adresse du dossier actuel\nNVDA+Shift+V Une pression : Copier le contenu\nNVDA+Shift+V Deux pressions : Inverser la sélection\nNVDA+Shift+F2 : Renommer le fichier uniquement"
		},
		{
			"language": "ru",
			"displayName": "xPlorer",
			"description": "Улучшение доступа к Проводнику Windows.\nГорячие клавиши:\nNVDA+Shift+X : Открыть контекстное меню xPlorer\nNVDA+Shift+Z Одно нажатие : Озвучить размер\nNVDA+Shift+Z Два нажатия : Сжать в Zip\nNVDA+Shift+C Одно нажатие : Копировать имена выбранных файлов и папок\nNVDA+Shift+C Два нажатия : Копировать путь из адресной строки текущей папки\nNVDA+Shift+V Одно нажатие : Копировать содержимое\nNVDA+Shift+V Два нажатия : Инвертировать выделение\nNVDA+Shift+F2 : Переименовать только файл"
		}
	]
}

=== nvaccess/addon-datastore/addons/sonata_neural_voices/3.2.0.json
{
	"addonId": "sonata_neural_voices",
	"displayName": "Sonata Neural Voices",
	"URL": "https://github.com/austek/sonata-nvda/releases/download/v3.2.0/sonata_neural_voices-3.2.0.nvda-addon",
	"description": "Neural voices for NVDA based on Sonata",
	"sha256": "f3992cc63580e89d19624486e310826d1e8853c47541420cbf3196bf81b5efe1",
	"addonVersionName": "3.2.0",
	"addonVersionNumber": {
		"major": 3,
		"minor": 2,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Ali Ustek",
	"sourceURL": "https://github.com/austek/sonata-nvda",
	"license": "GPL v2",
	"homepage": "https://github.com/austek/sonata-nvda",
	"changelog": "First stable release of the maintenance fork. Adds NVDA 2026.1 compatibility (Python 3.13, 64-bit) by rebuilding the bundled gRPC, miniaudio, and cffi binaries. Fixes voice list URL handling, voice install regex for names containing digits, voice list refresh after a successful download, install-from-local-file UX and error messages, and adds a Visual C++ Redistributable pre-flight check.",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1785447789000,
	"translations": [
		{
			"language": "ru",
			"displayName": "Нейронные голоса Sonata",
			"description": "Нейронные голоса для NVDA на основе Sonata",
			"changelog": "First stable release of the maintenance fork. Adds NVDA 2026.1 compatibility (Python 3.13, 64-bit) by rebuilding the bundled gRPC, miniaudio, and cffi binaries. Fixes voice list URL handling, voice install regex for names containing digits, voice list refresh after a successful download, install-from-local-file UX and error messages, and adds a Visual C++ Redistributable pre-flight check."
		},
		{
			"language": "fr",
			"displayName": "Voix neuronales de Sonata",
			"description": "Voix neuronales pour NVDA basées sur Sonata",
			"changelog": "First stable release of the maintenance fork. Adds NVDA 2026.1 compatibility (Python 3.13, 64-bit) by rebuilding the bundled gRPC, miniaudio, and cffi binaries. Fixes voice list URL handling, voice install regex for names containing digits, voice list refresh after a successful download, install-from-local-file UX and error messages, and adds a Visual C++ Redistributable pre-flight check."
		},
		{
			"language": "es",
			"displayName": "Voces Neuronales Sonata",
			"description": "Voces neuronales para NVDA basado en Sonata",
			"changelog": "First stable release of the maintenance fork. Adds NVDA 2026.1 compatibility (Python 3.13, 64-bit) by rebuilding the bundled gRPC, miniaudio, and cffi binaries. Fixes voice list URL handling, voice install regex for names containing digits, voice list refresh after a successful download, install-from-local-file UX and error messages, and adds a Visual C++ Redistributable pre-flight check."
		}
	]
}

=== nvaccess/addon-datastore/addons/dateParser/1.1.0.json
{
	"addonId": "dateParser",
	"displayName": "Parses and speaks date and time expressions",
	"URL": "https://github.com/OnjLouis/dateParser/releases/download/v1.1.0/dateParser-1.1.0.nvda-addon",
	"description": "Adds a global NVDA script (NVDA+Alt+E) to parse natural date and duration expressions and speak the result.",
	"sha256": "b1bbc8a61c1e17e8b6f5461efb188ec1b6c74cd3b3159955f149ddffa07e095e",
	"addonVersionName": "1.1.0",
	"addonVersionNumber": {
		"major": 1,
		"minor": 1,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 1
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Andre Louis",
	"sourceURL": "https://github.com/OnjLouis/dateParser",
	"license": "GPL v2",
	"homepage": "https://github.com/OnjLouis/dateParser",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1789913172000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/leanCalendar/0.2.3.json
{
	"addonId": "leanCalendar",
	"displayName": "leanCalendar",
	"URL": "https://github.com/cary-rowen/leanCalendar/releases/download/v0.2.3/leanCalendar-0.2.3.nvda-addon",
	"description": "Reports Chinese lunar date, solar terms, Gregorian date and time details, and an interactive calendar query dialog.",
	"sha256": "2e370a5e8e0cf5736c0cdfa271a7d1bad02bdf56e03a5333563af3d2cab66f44",
	"addonVersionName": "0.2.3",
	"addonVersionNumber": {
		"major": 0,
		"minor": 2,
		"patch": 3
	},
	"minNVDAVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Cary-rowen <manchen_0528@outlook.com>",
	"sourceURL": "https://github.com/cary-rowen/leanCalendar",
	"license": "GPL v2",
	"homepage": "https://github.com/cary-rowen/leanCalendar",
	"changelog": "### 0.2.3\n\n* Dependent Updates.",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1782011377000,
	"translations": [
		{
			"language": "zh",
			"displayName": "简易万年历",
			"description": "读出农历日期、节气、公历日期和时间详情，并提供可交互的万年历查询对话框。",
			"changelog": "### 0.2.3\n\n* Dependent Updates."
		}
	]
}

=== nvaccess/addon-datastore/addons/timezone/3.2.0.json
{
	"addonId": "timezone",
	"displayName": "Time Zoner",
	"URL": "https://github.com/munawarb/NVDA-Time-Zoner/releases/download/v3.02/timezone-3.02.nvda-addon",
	"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones.",
	"sha256": "83df8d9e50e299cc9a11edd8b7531f82b5b7f222c45cfb7f0087c55c7e9023a6",
	"addonVersionName": "3.02",
	"addonVersionNumber": {
		"major": 3,
		"minor": 2,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2021,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Munawar Bijani",
	"sourceURL": "https://github.com/munawarb/NVDA-Time-Zoner",
	"license": "GPL v2",
	"homepage": "https://github.com/munawarb/NVDA-Time-Zoner",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "en",
			"displayName": "Time Zoner",
			"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones."
		},
		{
			"language": "pt_BR",
			"displayName": "An\u00fancio de horas em diferentes fusos hor\u00e1rios",
			"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones."
		},
		{
			"language": "pt_PT",
			"displayName": "An\u00fancio de horas em diferentes fusos hor\u00e1rios",
			"description": "Announces the time and date in selected timezones. Use the Settings dialog to set timezones you want to hear. After you do this, press NVDA+ALT+UP/DOWN ARROW to cycle through your timezone ring and hear times in your selected timezones."
		}
	]
}

=== nvaccess/addon-datastore/addons/Access8Math/4.5.0.json
{
	"addonId": "Access8Math",
	"displayName": "Access8Math",
	"URL": "https://github.com/tsengwoody/Access8Math/releases/download/v4.5/Access8Math-4.5.nvda-addon",
	"description": "Allows access math content written by MathML ; Allows write math content by LaTeX",
	"sha256": "6704f0a11d0057766901b7e94ccb20a16bd2c21169384fdfe5193853dfdd0a7d",
	"addonVersionName": "4.5",
	"addonVersionNumber": {
		"major": 4,
		"minor": 5,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 3,
		"patch": 3
	},
	"channel": "stable",
	"publisher": "Tseng Woody",
	"sourceURL": "https://github.com/tsengwoody/Access8Math",
	"license": "GPL v2",
	"homepage": "https://github.com/tsengwoody/Access8Math",
	"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths.",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1774624588000,
	"translations": [
		{
			"language": "de",
			"displayName": "Access8Math",
			"description": "Ermöglicht es, mathematische Inhalte im MathML-Format zu lesen sowie Math-ML mittels Latex zu erzeugen",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "es",
			"displayName": "Access8Math",
			"description": "Permite acceder a contenido matemático escrito en MathML; permite escribir contenido matemático en LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "fr",
			"displayName": "Access8Math",
			"description": "Permet l'accès au contenu mathématique écrit en MathML ; Permet d'écrire du contenu mathématique en LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "gl",
			"displayName": "Access8Math",
			"description": "Permite acesar a contido matemático escrebido en MathML; permite escrebir contido matemático en LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "it",
			"displayName": "Access8Math",
			"description": "Consente di accedere a contenuti matematici scritti con MathML; Consente di scrivere contenuti matematici con LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "pt_BR",
			"displayName": "Access8Math",
			"description": "Permite acessar conteúdo matemático escrito com MathML; Permite escrever conteúdo matemático através de LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "pt_PT",
			"displayName": "Access8Math",
			"description": "Permite aceder a conteúdos matemáticos escritos em MathML; Permite escrever conteúdos matemáticos em LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "ro",
			"displayName": "Access8Math",
			"description": "Permite accesul la conținut matematic scris de MathML; Permite scrierea conținutului matematic prin LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "ru",
			"displayName": "Access8Math",
			"description": "Предоставляет доступ к математическим выражениям, написанным на MathML; позволяет записывать математические выражения с помощью LaTeX",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "tr",
			"displayName": "Access8Math",
			"description": "MathML ile yazılan matematik içeriğine erişime sağlar ve LaTeX ile matematik içeriği oluşturmaya izin verir",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "zh_CN",
			"displayName": "Access8Math",
			"description": "可以閱讀 MathML 編寫的數學內容；可以使用 LaTeX 書寫數學內容",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		},
		{
			"language": "zh_TW",
			"displayName": "Access8Math",
			"description": "允許閱讀 MathML 編寫的數學內容；允許通過 LaTeX 書寫數學內容",
			"changelog": "Added an HTML color scheme setting for preview and export output.\nRefactored the math provider and writer layers to improve package structure and maintainability.\nSimplified bundled dependencies by removing unused web/template shims and cleaning up import paths."
		}
	]
}
