=== nvaccess/addon-datastore/validation/_validate/addonVersion_schema.json
{
	"examples": [
		{
			"addonId": "easyAddonTech.XYZ",
			"addonVersionNumber": {
				"major": 21,
				"minor": 6,
				"patch": 0
			},
			"addonVersionName": "21.6.0",
			"displayName": "My addon",
			"publisher": "easyAddonTech",
			"description": "Makes doing XYZ easier",
			"homepage": "https://github.com/nvaccess/addon-datastore",
			"minNVDAVersion": {
				"major": 2019,
				"minor": 3,
				"patch": 0
			},
			"lastTestedVersion": {
				"major": 2020,
				"minor": 4,
				"patch": 0
			},
			"channel": "beta",
			"URL": "https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon",
			"sha256": "69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82",
			"sourceURL": "https://github.com/nvaccess/addon-datastore/",
			"license": "GPL v2",
			"licenseURL": "https://github.com/nvaccess/addon-datastore/license.MD",
			"changelog": "New features",
			"translations": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248",
			"submissionTime": 1723523492363
		}
	],
	"title": "Root",
	"type": "object",
	"description": "Information about an addon release",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"required": [
		"addonId",
		"addonVersionNumber",
		"addonVersionName",
		"displayName",
		"publisher",
		"description",
		"minNVDAVersion",
		"lastTestedVersion",
		"channel",
		"URL",
		"sha256",
		"sourceURL",
		"license",
		"translations"
	],
	"properties": {
		"addonId": {
			"default": "",
			"description": "The ID for the addon, matches the name field in the addon manifest and the folder name for the submission.",
			"examples": [
				"easyAddonTech.XYZ"
			],
			"title": "The ID for the addon",
			"type": "string"
		},
		"addonVersionNumber": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The addon version number",
			"description": "Pure numerical representation of the version being released.",
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			]
		},
		"addonVersionName": {
			"title": "The addon version name",
			"description": "The addon version being released. Must match the version in the addon manifest and the file name for the submission.",
			"type": "string",
			"default": "",
			"examples": [
				"21.6.0",
				"21.6",
				"21.06"
			]
		},
		"displayName": {
			"default": "",
			"description": "The name that will be displayed in English for the addon.",
			"examples": [
				"My addon"
			],
			"title": "The display name (en) of the addon",
			"type": "string"
		},
		"publisher": {
			"default": "",
			"description": "The name of the individual, group, or company responsible for the addon.",
			"examples": [
				"NV Access"
			],
			"title": "The publisher name for the addon",
			"type": "string"
		},
		"description": {
			"default": "",
			"description": "The English description of the addon that will be displayed for the addon.",
			"examples": [
				"Makes doing XYZ easier"
			],
			"title": "The description (en) of the addon",
			"type": "string"
		},
		"homepage": {
			"default": "",
			"description": "If the addon has a homepage where users can get more information about the addon, you can specify it here.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore"
			],
			"pattern": "^https:.*",
			"title": "The homepage URL for the addon.",
			"type": "string"
		},
		"minNVDAVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"default": {},
			"title": "The minNVDAVersion schema",
			"description": "The addon will not work with versions of NVDA prior to this version.",
			"examples": [
				{
					"major": 2019,
					"minor": 3,
					"patch": 0
				}
			]
		},
		"lastTestedVersion": {
			"$ref": "#/$defs/canonicalVersion",
			"title": "The lastTestedVersion schema",
			"description": "The add-on has been tested up to and including this version of NVDA",
			"default": {},
			"examples": [
				{
					"major": 2020,
					"minor": 4,
					"patch": 0
				}
			]
		},
		"channel": {
			"default": "",
			"description": "Used to define pre-release (beta) add-ons. Should be either 'stable', 'beta' or 'dev'",
			"examples": [
				"beta"
			],
			"title": "The channel for the addon",
			"enum": [
				"stable",
				"beta",
				"dev"
			],
			"type": "string"
		},
		"URL": {
			"default": "",
			"description": "To allow directly downloading the *.nvda-addon file. The URL should remain valid indefinitely. GitHub release URLs are recommended.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/releases/download/v0.1.0/myAddon.nvda-addon"
			],
			"title": "The URL to download the add-on.",
			"type": "string"
		},
		"sha256": {
			"default": "",
			"description": "Use the python script '_tools/genSha256.py' to generate this value.",
			"examples": [
				"69D84CA8899800A5575CE31798293CD4FEBAB1D734A07C2E51E56A28E0DF8C82"
			],
			"title": "The sha256 for the *.nvda-addon file.",
			"type": "string"
		},
		"sourceURL": {
			"default": "",
			"description": "Allows reviewers to inspect the source code for common issues.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/"
			],
			"title": "The URL for the add-on source",
			"type": "string"
		},
		"license": {
			"default": "",
			"description": "The short name of the license.",
			"examples": [
				"GPL v2"
			],
			"title": "The short name of the license for the addon",
			"type": "string"
		},
		"licenseURL": {
			"default": "",
			"description": "A URL to the full license for the addon.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/license.MD"
			],
			"title": "The URL of the license",
			"type": "string"
		},
		"changelog": {
			"default": "",
			"description": "Changes between the previous and the current version",
			"examples": [
				"New feature"
			],
			"title": "Add-on changelog (en)",
			"type": "string"
		},
		"legacy": {
			"default": false,
			"description": "Legacy add-ons have invalid data or manifest. Legacy add-ons are not listed in the NVDA add-on store.",
			"examples": [
				true
			],
			"title": "Mark add-on as legacy",
			"type": "boolean"
		},
		"translations": {
			"default": [],
			"description": "A collection of translations generated from localized add-on manifests",
			"examples": [
				[
					{
						"language": "de",
						"displayName": "Mein Addon",
						"description": "erleichtert das Durchführen von xyz",
						"changelog": "Neue Funktionen"
					}
				]
			],
			"title": "Translations",
			"type": "array",
			"items": {
				"$ref": "#/$defs/translation"
			}
		},
		"reviewUrl": {
			"default": "",
			"description": "A URL to the discussion comment to review the add-on version.",
			"examples": [
				"https://github.com/nvaccess/addon-datastore/discussions/1942#discussioncomment-7453248"
			],
			"title": "Discussion comment URL",
			"type": "string"
		},
		"submissionTime": {
			"default": 0,
			"description": "Timestamp in milliseconds, corresponding to the submission time of the add-on",
			"examples": [
				1723523492363
			],
			"title": "Submission time",
			"type": "number"
		},
		"vtScanUrl": {
			"default": "",
			"description": "A URL to the Virus Total scan for the add-on version.",
			"examples": [
				"https://www.virustotal.com/gui/file/3fda88d598e9747b2dfadfdfb8930a737c0049e9782392bffcd59ef668821547"
			],
			"title": "VirusTotal scan URL",
			"type": "string"
		},
		"scanResults": {
			"default": {},
		"description": "Results from VirusTotal scanning.",
			"examples": [
				{
					"virusTotal": {}
				}
			],
			"title": "Scan results",
			"type": "object"
		}
	},
	"$defs": {
		"canonicalVersion": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"major": 21,
					"minor": 6,
					"patch": 0
				}
			],
			"required": [
				"major",
				"minor",
				"patch"
			],
			"properties": {
				"major": {
					"default": 0,
					"description": "'major' in major.minor.patch",
					"examples": [
						21,
						2019,
						2021
					],
					"title": "The 'major' part of the version number.",
					"type": "integer"
				},
				"minor": {
					"default": 0,
					"description": "The 'minor' part in major.minor.patch",
					"examples": [
						3
					],
					"title": "The 'minor' part of the version number.",
					"type": "integer"
				},
				"patch": {
					"default": 0,
					"description": "The 'patch' part in major.minor.patch",
					"examples": [
						0
					],
					"title": "The 'patch' part of the version number.",
					"type": "integer"
				}
			}
		},
		"translation": {
			"default": {},
			"type": "object",
			"examples": [
				{
					"language": "de",
					"displayName": "Mein Addon",
					"description": "erleichtert das Durchführen von xyz",
					"changelog": "Neue Funktionen"
				}
			],
			"required": [
				"language",
				"displayName",
				"description"
			],
			"properties": {
				"language": {
					"default": "",
					"description": "Language code supported by NVDA",
					"examples": [
						"de",
						"pt_BR"
					],
					"title": "Language code",
					"type": "string"
				},
				"displayName": {
					"default": "",
					"description": "The translated name that will be displayed for the addon.",
					"examples": [
						"Mein Addon"
					],
					"title": "Translated display name",
					"type": "string"
				},
				"description": {
					"default": "",
					"description": "Translated description that will be displayed for the addon.",
					"examples": [
						"erleichtert das Durchführen von xyz"
					],
					"title": "The translated description",
					"type": "string"
				},
				"changelog": {
					"default": "",
					"description": "Translated description of changes between the previous and this add-on version",
					"examples": [
						"Neue Funktionen"
					],
					"title": "The translated changelog",
					"type": "string"
				}
			}
		}
	}
}

=== nvaccess/addon-datastore/addons/radioCenter/1.5.2.json
{
  "addonId": "radioCenter",
  "displayName": "radioCenter",
  "URL": "https://github.com/DollaR84/radioCenter/releases/download/stable/radioCenter-1.5.2.nvda-addon",
  "description": "this addon allows you to play online radio stations",
  "sha256": "e915da26d7effbcbce1c924e96ed21a7309046c6d096bc82e2fcef859c527b19",
  "addonVersionName": "1.5.2",
  "addonVersionNumber": {
    "major": 1,
    "minor": 5,
    "patch": 2
  },
  "minNVDAVersion": {
    "major": 2021,
    "minor": 2,
    "patch": 0
  },
  "lastTestedVersion": {
    "major": 2024,
    "minor": 1,
    "patch": 0
  },
  "channel": "stable",
  "publisher": "Ruslan Dolovaniuk",
  "sourceURL": "https://github.com/DollaR84/radioCenter",
  "license": "GPL v2",
  "homepage": "https://github.com/DollaR84/radioCenter",
  "licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
  "translations": [
    {
      "language": "cz",
      "displayName": "radioCenter",
      "description": "tento addon v\u00e1m umo\u017e\u0148uje poslouchat online rozhlasov\u00e9 stanice"
    },
    {
      "language": "en",
      "displayName": "radioCenter",
      "description": "this addon allows you to play online radio stations"
    },
    {
      "language": "ru",
      "displayName": "radioCenter",
      "description": "\u044d\u0442\u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043f\u043e\u0437\u0432\u043e\u043b\u044f\u0435\u0442 \u0432\u0430\u043c \u0441\u043b\u0443\u0448\u0430\u0442\u044c \u043e\u043d\u043b\u0430\u0439\u043d \u0440\u0430\u0434\u0438\u043e\u0441\u0442\u0430\u043d\u0446\u0438\u0438"
    },
    {
      "language": "tr",
      "displayName": "radyo merkezi",
      "description": "bu eklenti \u00e7evrimi\u00e7i radyo istasyonlar\u0131n\u0131 \u00e7alman\u0131za olanak tan\u0131r."
    },
    {
      "language": "uk",
      "displayName": "radioCenter",
      "description": "\u0446\u0435 \u0434\u043e\u043f\u043e\u0432\u043d\u0435\u043d\u043d\u044f \u0434\u043e\u0437\u0432\u043e\u043b\u044f\u0454 \u0432\u0430\u043c \u0441\u043b\u0443\u0445\u0430\u0442\u0438 \u043e\u043d\u043b\u0430\u0439\u043d \u0440\u0430\u0434\u0456\u043e\u0441\u0442\u0430\u043d\u0446\u0456\u0457"
    }
  ],
  "reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/3763"
}

=== nvaccess/addon-datastore/addons/terminalAccess/1.0.45.json
{
	"addonId": "terminalAccess",
	"displayName": "Terminal Access for NVDA",
	"URL": "https://github.com/PratikP1/Terminal-Access-for-NVDA/releases/download/v1.0.45/terminalAccess-1.0.45.nvda-addon",
	"description": "Provides enhanced terminal accessibility for Windows Terminal and PowerShell, enabling screen reader users to efficiently navigate and interact with command-line interfaces. Inspired by TDSR (Terminal Data Structure Reader) and incorporates functionality from both TDSR and Speakup. Advanced features inspired by community suggestions and discussions.",
	"sha256": "0f4e154e7d76066a9e07d51f8c4b2c783deb6e500b0e51100e2e5cb929585dbc",
	"addonVersionName": "1.0.45",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 45
	},
	"minNVDAVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Pratik Patel",
	"sourceURL": "https://github.com/PratikP1/Terminal-Access-for-NVDA",
	"license": "GPL v3",
	"homepage": "https://github.com/PratikP1/Terminal-Access-for-NVDA",
	"licenseURL": "https://www.gnu.org/licenses/gpl-3.0.html",
	"submissionTime": 1771861058000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/InternetUsageMonitor/2.1.1.json
{
	"addonId": "InternetUsageMonitor",
	"displayName": "InternetUsageMonitor",
	"URL": "https://github.com/rayo-alcantar/InternetUsageMonitor/releases/download/2.1.1/InternetUsageMonitor-2.1.1.nvda-addon",
	"description": "Complemento para NVDA que monitorea el uso de internet.",
	"sha256": "5dd4b730565001b2f44efaf0857868e5c053a855813ddc375d10315e0bb831a8",
	"addonVersionName": "2.1.1",
	"addonVersionNumber": {
		"major": 2,
		"minor": 1,
		"patch": 1
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Angel Alc\u00e1ntar",
	"sourceURL": "https://github.com/rayo-alcantar/InternetUsageMonitor",
	"license": "GPL v2",
	"homepage": "https://github.com/rayo-alcantar/InternetUsageMonitor/",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [
		{
			"language": "en",
			"displayName": "InternetUsageMonitor",
			"description": "This addon for NVDA allows you to monitor internet usage."
		},
		{
			"language": "ru",
			"displayName": "\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442-\u043c\u043e\u043d\u0438\u0442\u043e\u0440",
			"description": "\u042d\u0442\u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043f\u043e\u0437\u0432\u043e\u043b\u044f\u0435\u0442 \u043e\u0442\u0441\u043b\u0435\u0436\u0438\u0432\u0430\u0442\u044c \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435 \u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u0430."
		},
		{
			"language": "uk",
			"displayName": "InternetUsageMonitor",
			"description": "\u0414\u043e\u0434\u0430\u0442\u043e\u043a \u0434\u043b\u044f NVDA, \u044f\u043a\u0438\u0439 \u0432\u0456\u0434\u0441\u0442\u0435\u0436\u0443\u0454 \u0432\u0438\u043a\u043e\u0440\u0438\u0441\u0442\u0430\u043d\u043d\u044f \u0406\u043d\u0442\u0435\u0440\u043d\u0435\u0442\u0443."
		}
	]
}

=== nvaccess/addon-datastore/addons/tiflotecniaVoices/4.1.1.json
{
	"addonId": "tiflotecniaVoices",
	"displayName": "Tiflotecnia voices for NVDA",
	"URL": "https://github.com/ruifontes/tiflotecniaVoices/releases/download/4.1.1/tiflotecniaVoices-4.1.1.nvda-addon",
	"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices.",
	"sha256": "fd0a68c69ecc2d440d4caf8a5f1015dcef62bbe3f0d42fb0fb473ad61dfdd4aa",
	"addonVersionName": "4.1.1",
	"addonVersionNumber": {
		"major": 4,
		"minor": 1,
		"patch": 1
	},
	"minNVDAVersion": {
		"major": 2023,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "ruifontes",
	"sourceURL": "https://github.com/ruifontes/tiflotecniaVoices",
	"license": "GPL v2",
	"homepage": "https://www.tiflotecnia.com",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1749925143000,
	"translations": [
		{
			"language": "de",
			"displayName": "Tiflotecnia-Stimmen für NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "es",
			"displayName": "Voces de tiflotecnia para NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "he",
			"displayName": "קולות Tiflotecnia עבור NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "hr",
			"displayName": "Tiflotecnia voices for NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "it",
			"displayName": "Voci di Tiflotecnia per NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "ja",
			"displayName": "Tiflotecnia voices for NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "pl",
			"displayName": "Głosy Tiflotecnia dla NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "pt",
			"displayName": "Vozes Tiflotecnia para o NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "ru",
			"displayName": "Голоса Tiflotecnia для NVDA",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "tr",
			"displayName": "NVDA için Tiflotecnia sesleri",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		},
		{
			"language": "zh_CN",
			"displayName": "NVDA 的 Tiflotecnia 语音",
			"description": "Tiflotecnia voices for NVDA\nNVDA driver to the Cerence Embedded TTS synth\nLicense required to use the voices."
		}
	],
	"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/5322",
	"vtScanUrl": "https://www.virustotal.com/gui/file/fd0a68c69ecc2d440d4caf8a5f1015dcef62bbe3f0d42fb0fb473ad61dfdd4aa"
}

=== nvaccess/addon-datastore/addons/freeradio/2026.20.6.json
{
	"addonId": "freeradio",
	"displayName": "freeRadio",
	"URL": "https://github.com/Surveyor123/freeradio/releases/download/v2026.20.6/freeradio-2026.20.6.nvda-addon",
	"description": "FreeRadio is an internet radio add-on for NVDA that provides seamless access to thousands of stations via the Radio Browser open directory. It features a fully accessible station browser with search, country filter, favourites management, and per-station audio profiles. Playback is handled by a prioritised backend chain (BASS, VLC, PotPlayer, Windows Media Player) with support for volume control, audio effects, output device selection, and simultaneous audio mirroring to a second device. Additional features include instant and scheduled recording, sleep and alarm timers, automatic ICY metadata announcements, Shazam-based music recognition, and a liked-songs log. All controls and shortcuts are designed for NVDA accessibility.",
	"sha256": "68971ed8c9ddf662b50e3f07687a0ff37634e860f5fd43f45d21d48d51b24657",
	"addonVersionName": "2026.20.6",
	"addonVersionNumber": {
		"major": 2026,
		"minor": 20,
		"patch": 6
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 1,
		"patch": 1
	},
	"channel": "stable",
	"publisher": "Çağrı Doğan <cagrid@hotmail.com>",
	"sourceURL": "https://github.com/Surveyor123/freeradio",
	"license": "GPL v2",
	"homepage": "https://github.com/Surveyor123/freeradio",
	"changelog": "\n### New Features\n\n- **Time-shift buffer**: Rewind and fast-forward live radio like a DVR, using a rolling ~10-minute buffer. Enable it from Settings or toggle it instantly with `Ctrl+Win+T`. Rewind 15 seconds with `Ctrl+Win+J`; fast-forward 15 seconds with `Ctrl+Win+K` — reaching the live edge automatically returns you to normal live playback.\n- Time-shift now supports **HLS (`.m3u8`) stations** in addition to plain HTTP/HTTPS and Shoutcast/Icecast (ICY) streams — segments are downloaded and reassembled into the same rewindable buffer.\n\n### Fixes\n\n- Fixed time-shift capture (and recording) failing with an SSL certificate error on stations whose server presents an expired or otherwise invalid TLS certificate.\n\n### Documentation\n\n- Added a full \"Time-Shift (Rewind Live Radio)\" section to the README, plus new shortcut and settings table entries.\n",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1783777135000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/TextMarksTheSpot/1.0.18.json
{
	"addonId": "TextMarksTheSpot",
	"displayName": "Text Marks the Spot",
	"URL": "https://github.com/WebFriendlyHelp/TextMarksTheSpot/releases/download/v1.0.18/TextMarksTheSpot-1.0.18.nvda-addon",
	"description": "Get to the actual content on a web page without working so hard to find it. Hands off. Let the page load, listen for the short beeps, and you're at the start of the article. NVDA reads the first paragraph. Press Z to skim forward, Shift+Z to jump back to the start, NVDA+Z to turn the add-on off on a specific site. Runs locally, no network calls.",
	"sha256": "78bd7fea235bc24f133a6c94617337798ca0b3a6a1a1f84648ee06cf83230f82",
	"addonVersionName": "1.0.18",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 18
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2026,
		"minor": 3,
		"patch": 0
	},
	"channel": "stable",
	"publisher": "Casey Mathews",
	"sourceURL": "https://github.com/WebFriendlyHelp/TextMarksTheSpot",
	"license": "GPL v2",
	"homepage": "https://github.com/WebFriendlyHelp/TextMarksTheSpot",
	"changelog": "Pages that open with a real introduction land on it again, and the add-on is tested with NVDA 2026.3.\n\nA \"Features\" or \"Overview\" heading no longer jumps you past the introduction. On a shopping page, the description usually sits under a heading such as \"About this item\", \"Description\" or \"Features\", with clutter above it, so the add-on gives those headings priority. It gave them priority even on pages that had already opened with several paragraphs of real writing. NVDA's own What's New page put you on the second bullet under \"New Features\" instead of the summary of the release, and a getting-started guide landed more than sixty lines down on a feature list. Those headings now only take over when the page has not already started with its own introduction.\nRemote Incident Manager stops beeping at you. Its home screen shows up to NVDA as a web page with nothing on it, so every time it came up, the add-on went looking, found nothing, and played the two low beeps. It now leaves that screen alone. Z still works there if you ever want it.\nTested with NVDA 2026.3. Nothing needed changing for it. The add-on still runs on NVDA 2024.1 and newer, on both the 32-bit builds up to 2025.3 and the 64-bit builds from 2026.1 on.\n\nKnown gaps, unchanged from 1.0.17: a video row that also carries a written description under each video can still trip the headline wall, so some search results pages land on a video. Consent banners that never say what they store, the \"We value your privacy\" wording, are still not caught, and that costs you one press of Down Arrow. On some articles the cursor lands on the author's biography instead of the story; recipe sites can still land on a marketing line or a reader's review; the Verge and TechCrunch home pages lead with a large featured story and land on a headline further down the list; single-field sign-in pages that ask for your email first still get no landing (the two low beeps); and script-drawn result widgets like the fast.com speed test are still not detected.",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1793034786000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/programRAMReporter/1.0.0.json
{
	"addonId": "programRAMReporter",
	"displayName": "Program RAM Usage Reporter",
	"URL": "https://github.com/Ninjacoder42/programRAMReporter/releases/download/%23RAMUsageReporter/programRAMReporter.nvda-addon",
	"description": "This add-on allows you to check the RAM usage of your currently focused program.\nPress NVDA+Shift+9 to hear the current program's memory usage.",
	"sha256": "5961a2c8d16e697f6dbfbefd13ee65583ea5781a6bc30eb7527447a286d0263d",
	"addonVersionName": "1.0.0",
	"addonVersionNumber": {
		"major": 1,
		"minor": 0,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2019,
		"minor": 3,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2024,
		"minor": 1,
		"patch": 0
	},
	"channel": "dev",
	"publisher": "Justin",
	"sourceURL": "https://github.com/Ninjacoder42/programRAMReporter",
	"license": "GPL v2",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"submissionTime": 1729889259000,
	"translations": []
}

=== nvaccess/addon-datastore/addons/showSelectionWhenBrailleTetheredToReview/2024.914.0.json
{
	"addonId": "showSelectionWhenBrailleTetheredToReview",
	"displayName": "Show selection when braille is tethered to review",
	"URL": "https://github.com/burmancomp/show-selection-when-braille-tethered-to-review/releases/download/v2024.0914.0/showSelectionWhenBrailleTetheredToReview-2024.0914.0.nvda-addon",
	"description": "This is a beta version, and there may be issues.\nThere are likely very few testers which means that more or less use cases are\nnot tested. One such case is using braille input.\nIt Shows selection with dots 7 and 8 in edit controls and documents when\nbraille is tethered to review.",
	"sha256": "e040f018df16f211493c689ad24f075418362f39f884967fbecb08789a0d3c08",
	"addonVersionName": "2024.0914.0",
	"addonVersionNumber": {
		"major": 2024,
		"minor": 914,
		"patch": 0
	},
	"minNVDAVersion": {
		"major": 2024,
		"minor": 2,
		"patch": 0
	},
	"lastTestedVersion": {
		"major": 2025,
		"minor": 1,
		"patch": 0
	},
	"channel": "beta",
	"publisher": "Burman's Computer And Education Ltd.",
	"sourceURL": "https://github.com/burmancomp/show-selection-when-braille-tethered-to-review/",
	"license": "GPL v2",
	"homepage": "https://github.com/burmancomp/show-selection-when-braille-tethered-to-review",
	"licenseURL": "https://www.gnu.org/licenses/gpl-2.0.html",
	"translations": [],
	"reviewUrl": "https://github.com/nvaccess/addon-datastore/discussions/3762"
}
